### ISSUE TITLE
issue again after update

### ISSUE THREAD

**Issue by Nap4k** [HDInnovations/UNIT3D#676]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [x] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: v.1.9

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.https://paste.laravel.io/a21b5215-7587-44fd-ac27-63dee9f344c5
2.https://paste.laravel.io/c554911d-5b17-4037-a596-11af1a400736
3.just simply updayed start giving issues

**Comment by Nap4k** [comment]
==================================================
Installing Composer Packages
==================================================

composer install
[============================] (Done!)
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bandwidth-throttle/token-bucket 2.0.0 -> satisfiable by bandwidth-throttle/token-bucket[2.0.0].
    - bandwidth-throttle/token-bucket 2.0.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/15-xml.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-curl.ini
    - /etc/php/7.2/cli/conf.d/20-dom.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gd.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-intl.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-mbstring.ini
    - /etc/php/7.2/cli/conf.d/20-mysqli.ini
    - /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-simplexml.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.2/cli/conf.d/20-wddx.ini
    - /etc/php/7.2/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.2/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.2/cli/conf.d/20-xsl.ini
    - /etc/php/7.2/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by HDVinnie** [comment]
kinda self explanatory no?

your missing a php extension. `sudo apt install php7.3-bcmath`

change 7.3 depending on what ver of php you have installed

**Comment by Nap4k** [comment]
Error: Cannot overwrite non-directory '/var/www/html/public/img/joypixels' with directory '/var/www/html/node_modules/emojione-assets/png/64'.
    at onDir (/var/www/html/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:11)
    at getStats (/var/www/html/node_modules/fs-extra/lib/copy-sync/copy-sync.js:43:37)
    at startCopy (/var/www/html/node_modules/fs-extra/lib/copy-sync/copy-sync.js:36:10)
    at Object.copySync (/var/www/html/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:10)
    at File.copyTo (/var/www/html/node_modules/laravel-mix/src/File.js:191:12)
    at FileCollection.copyTo (/var/www/html/node_modules/laravel-mix/src/FileCollection.js:83:24)
    at src.forEach.file (/var/www/html/node_modules/laravel-mix/src/FileCollection.js:77:38)
    at Array.forEach (<anonymous>)
    at FileCollection.copyTo (/var/www/html/node_modules/laravel-mix/src/FileCollection.js:77:17)
    at CopyFilesTask.run (/var/www/html/node_modules/laravel-mix/src/tasks/CopyFilesTask.js:15:20)
    at CustomTasksPlugin.runTask (/var/www/html/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:35:14)
    at Mix.tasks.forEach.task (/var/www/html/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:11:44)
    at Array.forEach (<anonymous>)
    at compiler.plugin.stats (/var/www/html/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:11:23)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/var/www/html/node_modules/webpack/lib/Compiler.js:267:22)
    at Compiler.emitRecords (/var/www/html/node_modules/webpack/lib/Compiler.js:449:39)
    at emitAssets.err (/var/www/html/node_modules/webpack/lib/Compiler.js:261:10)
    at hooks.afterEmit.callAsync.err (/var/www/html/node_modules/webpack/lib/Compiler.js:435:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/var/www/html/node_modules/webpack/lib/Compiler.js:432:27)
    at /var/www/html/node_modules/neo-async/async.js:2813:7
    at done (/var/www/html/node_modules/neo-async/async.js:3521:9)
    at /var/www/html/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-14T18_02_27_576Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-14T18_02_27_618Z-debug.log
root@vmi219609:/var/www/html#

**Comment by HDVinnie** [comment]
resolved
